2024-08-06 18:55:07.792 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/workspace/blog/.pixi/envs'
	at Object.readdirSync (node:fs:1515:26)
	at /workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/out/client/extension.js:2:574598
	at /workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/out/client/extension.js:2:574789
	at Array.map (<anonymous>)
	at d.initWatchers (/workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/out/client/extension.js:2:574507)
	at async d.ensureWatchersReady (/workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/out/client/extension.js:2:536827)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/workspace/blog/.pixi/envs'
}
2024-08-06 18:55:07.792 [error] Dir "/workspace/blog/.pixi/envs" is not watchable (directory does not exist)
2024-08-06 18:55:07.851 [info] Default formatter is set to null for workspace /workspace/blog
2024-08-06 18:55:07.919 [info] > conda info --json
2024-08-06 18:55:07.933 [info] > ~/.pyenv/versions/3.12.2/bin/python -I /workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/python_files/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2024.10.0-universal/python_files/interpreterInfo.py
2024-08-06 18:55:07.965 [info] Python interpreter path: ~/.pyenv/versions/3.12.2/bin/python
2024-08-06 18:55:08.157 [info] > ~/.pyenv/bin/pyenv which python
2024-08-06 18:55:08.157 [info] cwd: .
2024-08-06 18:55:09.831 [info] Starting Jedi language server for blog.
2024-08-06 18:55:10.010 [info] > pixi --version
2024-08-06 18:55:10.010 [error] [Error: spawn pixi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pixi',
  path: 'pixi',
  spawnargs: [ '--version' ]
}
2024-08-06 18:55:10.010 [warning] could not find a pixi interpreter for the interpreter at /home/gitpod/.pyenv/versions/3.12.2/bin/python
2024-08-06 18:55:10.010 [info] Send text to terminal: pyenv shell 3.12.2
2024-08-06 18:55:10.011 [warning] could not find a pixi interpreter for the interpreter at /home/gitpod/.pyenv/versions/3.12.2/bin/python
2024-08-06 18:55:10.011 [info] Send text to terminal: pyenv shell 3.12.2
2024-08-06 19:43:46.283 [warning] could not find a pixi interpreter for the interpreter at /home/gitpod/.pyenv/versions/3.12.2/bin/python
2024-08-06 19:43:46.284 [info] Send text to terminal: pyenv shell 3.12.2
2024-08-06 20:04:49.476 [warning] could not find a pixi interpreter for the interpreter at /home/gitpod/.pyenv/versions/3.12.2/bin/python
2024-08-06 20:04:49.476 [info] Send text to terminal: pyenv shell 3.12.2
2024-08-06 20:10:47.246 [warning] could not find a pixi interpreter for the interpreter at /home/gitpod/.pyenv/versions/3.12.2/bin/python
2024-08-06 20:10:47.246 [info] Send text to terminal: pyenv shell 3.12.2
